#! /bin/sh

setxkbmap -option caps:swapescape
feh --bg-scale ~/.local/share/wallpapers/spike_faye.png

pgrep -x xcompmgr > /dev/null || xcompmgr &
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x polybar > /dev/null || polybar &
pgrep -x 1password > /dev/null || 1password --silent &
pgrep -x playerctld > /dev/null || playerctld &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Emacs state=tiled
bspc rule -a iwgtk state=floating
bspc rule -a 1Password state=floating center=true
bspc rule -a discord desktop=IX

# aesthetic cmus location on desktop X
# can only have 1 cmus at a time anyways
pgrep -x cmus > /dev/null || \
  (bspc rule -a Alacritty -o desktop="X" \
                             state=floating \
                             rectangle="720x620+30+790" \
                             && alacritty -e cmus)
