#! /bin/sh

~/.fehbg &
setxkbmap -option "caps:swapescape"

fork_it () { nohup $@ >/dev/null 2>&1 & }

pgrep -x picom > /dev/null || fork_it picom
pgrep -x sxhkd > /dev/null || fork_it sxhkd
pgrep -x polybar > /dev/null || fork_it polybar
pgrep -x 1password > /dev/null || fork_it 1password --silent
pgrep -x playerctld > /dev/null || fork_it playerctld
pgrep -x dunst > /dev/null || fork_it dunst

pgrep -x window_gc.sh | xargs -r kill -9
fork_it ~/.config/bspwm/window_gc.sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3
bspc config normal_border_color $CAT_OVERLAY0
bspc config focused_border_color $CAT_LAVENDER
bspc config urgent_border_color $CAT_PEACH
bspc config presel_border_color $CAT_YELLOW

bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# electron garbage
bspc desktop '^9' -l monocle
bspc rule -a discord desktop='^9'
bspc rule -a spotify desktop='^9'

# steam
bspc rule -a steamwebhelper desktop='^8' follow=on
bspc rule -a steam desktop='^8' follow=on

bspc rule -a Emacs state=tiled
bspc rule -a iwgtk state=floating
bspc rule -a 1Password state=floating center=true
bspc rule -a "Google-chrome" desktop='^2' follow=on
bspc rule -a firefox desktop='^2' follow=on
bspc rule -a *:*:"Picture in picture" state=floating rectangle="512x288+2000+1100" border=off
bspc rule -a zenity state=floating
bspc rule -a *:*:"Friends List" state=floating
bspc rule -a cmus desktop='^10' state=floating rectangle="720x620+32+775"
bspc rule -a ncmpcpp desktop='^10' state=floating rectangle="720x620+32+775"
bspc rule -a zoom desktop='^4' state=floating center=on follow=on
bspc rule -a zoom:*:"zoom" desktop='^4' border=off
bspc rule -a art_viewer desktop='^10' state=floating follow=off focus=off

bspc config external_rules_command ~/.config/bspwm/external_rules.sh
